Update requirements.txt
Erro on streamlit app due to error message below:
ERROR: Could not find a version that satisfies the requirement install==1.3.5 (from versions: none)
ERROR: No matching distribution found for install==1.3.5